function [zd_1,zd_2] = R_sub_function(z1,z2)
%R_SUB_FUNCTION
%    [ZD_1,ZD_2] = R_SUB_FUNCTION(Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Sep-2017 17:22:57

t2 = z1.^2;
t3 = sqrt(3.0);
t4 = z2.^2;
zd_1 = t3.*z1.*1i+t2.*t3.*z2.*1.5625e-2i-t2.*t4.*z1.*1.82066430103337e-3i;
if nargout > 1
    zd_2 = t3.*z2.*-1i+t2.*t4.*z2.*1.82066430103337e-3i-t3.*t4.*z1.*1.5625e-2i;
end
