function [out1,out2] = R_sub_EM_function(z1,z2)
%R_SUB_EM_FUNCTION
%    [OUT1,OUT2] = R_SUB_EM_FUNCTION(Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Sep-2017 13:04:00

t2 = sqrt(6.0);
t3 = t2.*4.0e-1i;
out1 = z1.*(t3-1.0./5.0);
if nargout > 1
    out2 = -z2.*(t3+1.0./5.0);
end
