function [zd_1,zd_2] = R_sub_function(z1,z2)
%R_SUB_FUNCTION
%    [ZD_1,ZD_2] = R_SUB_FUNCTION(Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Mar-2019 18:34:12

t2 = z1.^2;
t3 = z2.^2;
zd_1 = z1.*(-1.5e-2+1.7319858544457i)+t2.*z2.*2.706430879887396e-2i+t2.*t3.*z1.*(-1.37340260437e-6-1.82111526820033e-3i);
if nargout > 1
    zd_2 = z2.*(-1.5e-2-1.7319858544457i)-t3.*z1.*2.706430879887396e-2i+t2.*t3.*z2.*(-1.37340260437e-6+1.82111526820033e-3i);
end
