function res = res_function(a,b,lambda_1,lambda_2,lambda_k)
%RES_FUNCTION
%    RES = RES_FUNCTION(A,B,LAMBDA_1,LAMBDA_2,LAMBDA_K)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Sep-2017 17:22:31

t2 = abs(a);
t3 = abs(b);
t4 = abs(lambda_1);
t5 = abs(lambda_2);
t6 = abs(lambda_k);
res = abs(-lambda_k+a.*lambda_1+b.*lambda_2).*1.0./sqrt(t2.^2+t3.^2+1.0).*1.0./sqrt(t4.^2+t5.^2+t6.^2);
