function dyn_sys = system_function(x_1,x_2,xd_1,xd_2)
%SYSTEM_FUNCTION
%    DYN_SYS = SYSTEM_FUNCTION(X_1,X_2,XD_1,XD_2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Sep-2017 13:04:01

t2 = x_1.^2;
dyn_sys = [xd_1;xd_2;x_1.*(-5.005)+x_2.*(8.01e2./2.0e2)-xd_1.*(4.0./5.0)+xd_2.*(2.0./5.0)-t2.*x_1.*(1.0./2.0);x_1.*(8.01e2./2.0e2)-x_2.*5.005+xd_1.*(2.0./5.0)-xd_2.*(4.0./5.0)];
